### ISSUE TITLE
A bug issue related to the _Density parameter.

### ISSUE THREAD

**Issue by Sakura-hana-bit** [AntonioNoack/Unity-SurfelGI#1]
Hello, dear AntonioNoack, your Surfels GI effect is impressive. Recently, I've been studying your code, and I've noticed that _Density should logically correlate with the radius of surfels. A larger radius should ideally generate fewer surfels on the screen, but in practice, _Density seems to significantly decrease performance. I've reviewed the source code and haven't identified any potential causes for this performance drop. I hope you can clarify my confusion.

**Comment by Sakura-hana-bit** [comment]
And I've found that it seems to be causing the bug in the process of “AccumulateSurfelEmissions”. I'm currently reviewing to see if there's anywhere causing this issue.

**Comment by AntonioNoack** [comment]
Density, as you have seen as well, increases the radius/overlap of the surfels. For the number of surfels, there is a different parameter, that then will scale them with that, too. Density is a relative parameter to that.

And yes, overlap is expensive, because each pixel has to be shaded many times then. The issue is commonly called "overdraw" in traditional computer graphics.

As for the visual result, a high density value will make things a little blurrier (and ofc slower), while a too-low density value may leave gaps (but is faster).
Doubling the density increases the shaded pixels for accumulation four-fold, so you can expect upto a four-times slowdown.

**Comment by AntonioNoack** [comment]
The parameter controlling the number of used surfels, which also controls their size, is called maxNumSurfels.

**Comment by Sakura-hana-bit** [comment]
Okay, I think I understand this process now. thank you..
